apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: Testing Tech Docs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: unknown
